frontier_exploration_turtlebot: CollisionDetector Class Reference
CollisionDetector Class Reference
class to find the the presence of the obstacle and to distinguish the position of the obstance in the front or rear of the turtlebot
#include <CollisionDetector.h>
Public Member Functions
CollisionDetector ()
constructor CollisionDetector class initializes values of CollisionFlag to 0
~CollisionDetector ()
destructor CollisionDetector class destroys CollisionDetector class objects when it goes out of scope.
void laserCallback (const sensor_msgs::LaserScan::ConstPtr &msg)
laser callback functionCheck :A call back function to read laserscan data and checks if the obstacle is within the vicinity of the robot and sets the CollisionFlag(0,1,2) based on the position of the object
int checkObstacles ()
returns the value stored in CollisionFlag
Private Attributes
int CollisionFlag
Detailed Description
class to find the the presence of the obstacle and to distinguish the position of the obstance in the front or rear of the turtlebot
Definition at line 46 of file CollisionDetector.h.
Constructor & Destructor Documentation
CollisionDetector::CollisionDetector ()
constructor CollisionDetector class initializes values of CollisionFlag to 0
Parameters
none
Returns
none
Definition at line 40 of file CollisionDetector.cpp.
References CollisionFlag.
CollisionDetector::~CollisionDetector ()
destructor CollisionDetector class destroys CollisionDetector class objects when it goes out of scope.
Parameters
none
Returns
none
Definition at line 45 of file CollisionDetector.cpp.
Member Function Documentation
int CollisionDetector::checkObstacles ()
returns the value stored in CollisionFlag
Parameters
none
Returns
int
Definition at line 95 of file CollisionDetector.cpp.
References CollisionFlag.
Referenced by PathPlanning::linearPathGenerator(), PathPlanning::spiralPathGenerator(), and TEST().
void CollisionDetector::laserCallback (const sensor_msgs::LaserScan::ConstPtr & msg)
laser callback functionCheck :A call back function to read laserscan data and checks if the obstacle is within the vicinity of the robot and sets the CollisionFlag(0,1,2) based on the position of the object
Parameters
msg of type sensor_msgs::LaserScan
Returns
none
Definition at line 48 of file CollisionDetector.cpp.
References CollisionFlag.
Referenced by PathPlanning::PathPlanning(), and TEST().
Member Data Documentation
int CollisionDetector::CollisionFlag private
Definition at line 49 of file CollisionDetector.h.
Referenced by checkObstacles(), CollisionDetector(), and laserCallback().
The documentation for this class was generated from the following files:
/home/saurav/ros_workspace/src/frontier_exploration_turtlebot/include/frontier_exploration_turtlebot/CollisionDetector.h
/home/saurav/ros_workspace/src/frontier_exploration_turtlebot/src/CollisionDetector.cpp