frontier_exploration_turtlebot: /home/saurav/ros_workspace/src/frontier_exploration_turtlebot/test/CollisionDetectorTest.cpp File Reference
CollisionDetectorTest.cpp File Reference
Tests the collisionDetector class methods.
#include <ros/ros.h>
#include <sensor_msgs/LaserScan.h>
#include <frontier_exploration_turtlebot/CollisionDetector.h>
#include <gtest/gtest.h>
#include <iostream>
Functions
TEST (CollisionDetectorTest, CollisionDetectorTest)
Tests constructor of the class CollisionDetector.
TEST (CollisionDetectorTest, laserCallbackTest)
Tests laserCallback method of the class CollisionDetector.
Detailed Description
Tests the collisionDetector class methods.
MIT License
Copyright (c) 2018 Saimouli Katragadda, Saurav Kumar
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Author
Saimouli Katragadda
Saurav Kumar
Copyright
MIT License
Definition in file CollisionDetectorTest.cpp.
Function Documentation
TEST (CollisionDetectorTest , CollisionDetectorTest)
Tests constructor of the class CollisionDetector.
Parameters
CollisionDetectorTest gtest framework
CollisionDetectorTest Name of the test
Returns
none
Definition at line 46 of file CollisionDetectorTest.cpp.
References CollisionDetector::checkObstacles().
TEST (CollisionDetectorTest , laserCallbackTest)
Tests laserCallback method of the class CollisionDetector.
Parameters
CollisionDetectorTest gtest framework
distanceCallbackTest Name of the test
Returns
none
Definition at line 58 of file CollisionDetectorTest.cpp.
References CollisionDetector::checkObstacles(), and CollisionDetector::laserCallback().