frontier_exploration_turtlebot: /home/saurav/ros_workspace/src/frontier_exploration_turtlebot/test/PathPlanningTest.cpp File Reference
PathPlanningTest.cpp File Reference
Tests the PathPlanning class methods.
#include <ros/ros.h>
#include <sensor_msgs/LaserScan.h>
#include <geometry_msgs/Twist.h>
#include <gtest/gtest.h>
#include <frontier_exploration_turtlebot/CollisionDetector.h>
#include <frontier_exploration_turtlebot/PathPlanning.h>
Functions
void testCallback (const geometry_msgs::Twist msg)
global function to store the twist msg value to global float variabls
TEST (PathPlanningTest, InitializationErrorTest)
Tests for initialization.
TEST (PathPlanningTest, spiralPathGeneratorTest)
Tests spiralPathGenerator method of the class PathPlanning.
TEST (PathPlanningTest, linearPathGeneratorTest)
Tests linearPathGenerator method of the class PathPlanning.
Variables
float linX = 0.0
float angZ
Detailed Description
Tests the PathPlanning class methods.
MIT License
Copyright (c) 2018 Saimouli Katragadda, Saurav Kumar
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Author
Saimouli Katragadda
Saurav Kumar
Copyright
MIT License
Definition in file PathPlanningTest.cpp.
Function Documentation
TEST (PathPlanningTest , InitializationErrorTest)
Tests for initialization.
Parameters
PathPlanningTest gtest framework
InitializationErrorTest Name of the test
Definition at line 59 of file PathPlanningTest.cpp.
TEST (PathPlanningTest , spiralPathGeneratorTest)
Tests spiralPathGenerator method of the class PathPlanning.
Parameters
PathPlanningTest gtest framework
spiralPathGeneratorTest Name of the test
Returns
none
Definition at line 70 of file PathPlanningTest.cpp.
References angZ, linX, PathPlanning::spiralPathGenerator(), and testCallback().
TEST (PathPlanningTest , linearPathGeneratorTest)
Tests linearPathGenerator method of the class PathPlanning.
Parameters
PathPlanningTest gtest framework
linearPathGeneratorTest Name of the test
Returns
none
Definition at line 116 of file PathPlanningTest.cpp.
References angZ, PathPlanning::linearPathGenerator(), linX, and testCallback().
void testCallback (const geometry_msgs::Twist msg)
global function to store the twist msg value to global float variabls
Parameters
const geometry_msgs::Twist msg
Returns
void
Definition at line 49 of file PathPlanningTest.cpp.
References angZ, and linX.
Referenced by TEST().
Variable Documentation
float angZ
Definition at line 42 of file PathPlanningTest.cpp.
Referenced by TEST(), and testCallback().
float linX = 0.0
Definition at line 42 of file PathPlanningTest.cpp.
Referenced by TEST(), and testCallback().